language: android
android:
  components:
    - android-28
    - build-tools-28.0.3

before_install:
  - chmod +x gradlew

# Extend compile timeout to 30 minutes; gwt easily takes 10+.
script: travis_wait 30 ./gradlew clean build -x android:validateSigningDebug
